"""Bundle the three board JSON files into data/boards.js.

The page loads data/boards.js as a plain <script> so it works from file://
without a server (fetch() of a local JSON file is blocked by the browser).
Run this after regenerating the boards with build_board.py.

    python scripts/make_boards_js.py
"""

import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(HERE, os.pardir, "data")
META_KEYS = ("season", "scoring", "teams", "replacement", "generated_from_seasons")


def main():
    boards, meta = {}, {}
    for fmt in ("ppr", "half", "std"):
        with open(os.path.join(DATA, "board_%s.json" % fmt), encoding="utf-8") as fh:
            d = json.load(fh)
        boards[fmt] = d["players"]
        meta[fmt] = {k: d[k] for k in META_KEYS}

    out = os.path.join(DATA, "boards.js")
    with open(out, "w", encoding="utf-8") as fh:
        fh.write("// Generated by scripts/make_boards_js.py from data/board_{ppr,half,std}.json.\n")
        fh.write("// Do not edit by hand.\n")
        fh.write("window.BOARD_META = " + json.dumps(meta, indent=1) + ";\n")
        fh.write("window.BOARDS = " + json.dumps(boards) + ";\n")

    print("wrote %s (%d bytes)" % (out, os.path.getsize(out)))


if __name__ == "__main__":
    main()
